### ISSUE TITLE
Capability to edit props without flow

### ISSUE THREAD

**Issue by danielmarino24i** [webcodesk/webcodesk#1]
It will be cool that the editor shows a window to edit prop values from components without feeding them through flow

**Comment by ipselon** [comment]
@danielmarino24i, it seems a cool idea. I'll try to figure out how to implement this. Thanks!

**Comment by ipselon** [comment]
@danielmarino24i, I added the ability to set the initial state of the component instance. Download 2 beta version.

<img width="1390" alt="screen shot 2019-02-28 at 16 26 39" src="https://user-images.githubusercontent.com/11865795/53573230-acedf880-3b75-11e9-92e0-faef7ab2e14d.png">

**Comment by danielmarino24i** [comment]
Thank you so much @ipselon
I will take a look, thanks in advance!
