### ISSUE TITLE
How do I install on non-debian / fedora based linux distros?

### ISSUE THREAD

**Issue by fr3fou** [webcodesk/webcodesk#3]
Mind providing a .tar.gz file or something like that for say Arch based distros etc?

**Comment by ipselon** [comment]
@fr3fou, did you try to download and install `.rpm` package for Fedora? 

I'm not familiar with all Linux distros, so I'd much appreciate if you tell that `.rpm` is working.

**Comment by ipselon** [comment]
I'm closing this because of no response.
