### ISSUE TITLE
i open market tab, there is nothing

### ISSUE THREAD

**Issue by Nicksxs** [webcodesk/webcodesk#5]
![image](https://user-images.githubusercontent.com/7351669/58091090-51bf2580-7bfb-11e9-857b-def14903194b.png)
and i click sign in , then click 'open account/create new'
see this
![image](https://user-images.githubusercontent.com/7351669/58091159-7adfb600-7bfb-11e9-9e64-0f7544939d01.png)

**Comment by ipselon** [comment]
@Nicksxs, the market service is shut down now. I'm sorry about that. However, you can build the distribution - now the source code is without the `Market` button.

**Comment by Nicksxs** [comment]
this is my first time to use this and i need to search some components to try build, how long will it be shut down, i can wait

**Comment by ipselon** [comment]
@Nicksxs, it seems that the market is shut down for a long time. So, I'd suggest you clone or download these projects with pre-created components:
* https://github.com/ipselon/firebase_auth_tutorial
* https://github.com/ipselon/prime_faces_react_todo_sample
* https://github.com/ipselon/application_layouts

**Comment by ipselon** [comment]
After you clone the project, run `yarn install` inside the project's directory, then open the project in Webcodesk.

**Comment by Nicksxs** [comment]
👌，i will try to build local, thanks a lot~

**Comment by Nicksxs** [comment]
@ipselon 
i clone the first project you listed, firebase_auth_tutorial, and met this problem
![image](https://user-images.githubusercontent.com/7351669/58143426-5cba9a00-7c7d-11e9-9dd6-4dff937e8878.png)

**Comment by ipselon** [comment]
@Nicksxs, try `yarn` instead.

**Comment by ipselon** [comment]
I'm closing this because it is not an actual issue anymore. Please take try the new version of Webcodesk: https://github.com/webcodesk/webcodesk-srv
